version: "3.7"
services:
    couchdb:
        build: ./couchdb
        networks:
            - theater
        ports:
            - "5984:5984"
    sinatra:
        build: ./sinatra
        networks:
            - theater
        ports:
            - "80:4567"
networks:
    theater:
        driver: bridge
